<a href="https://colab.research.google.com/github/Sanjeevraj01/DataScience/blob/main/Confidence_interval_19_12_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from scipy import stats
import numpy as np


In [11]:
from google.colab import files
uploaded = files.upload()

Saving glaxo_df to glaxo_df (1)


In [14]:
glaxo_df= pd.read_csv('glaxo_df')


In [16]:
glaxo_df


Date      Date.1    Close      gain
0     2010-01-05  2010-01-05  1616.80 -0.005444
1     2010-01-06  2010-01-06  1638.50  0.013422
2     2010-01-07  2010-01-07  1648.70  0.006225
3     2010-01-08  2010-01-08  1639.80 -0.005398
4     2010-01-11  2010-01-11  1629.45 -0.006312
...          ...         ...      ...       ...
1733  2016-12-26  2016-12-26  2723.50 -0.001283
1734  2016-12-27  2016-12-27  2701.75 -0.007986
1735  2016-12-28  2016-12-28  2702.15  0.000148
1736  2016-12-29  2016-12-29  2727.90  0.009529
1737  2016-12-30  2016-12-30  2729.80  0.000697

[1738 rows x 4 columns]

In [20]:
glaxo_df_ci = stats.norm.interval(0.95,loc = glaxo_df.Close.mean(),
scale = glaxo_df.Close.std())


In [21]:
np.round(glaxo_df_ci,4)

array([1473.9077, 3592.3995])

In [ ]:
# array([-0.0258,  0.0266]) = Gain
# array([1473.9077, 3592.3995]) = Close


In [22]:
from google.colab import files
uploaded = files.upload()

Saving beml_df to beml_df


In [23]:
beml_df = pd.read_csv('beml_df')

In [24]:
beml_df_ci = stats.norm.interval(0.95,loc = beml_df.gain.mean(),scale = beml_df.gain.std())
np.round(beml_df_ci,4)

array([-0.0515,  0.0521])